DWAPlannerROS: 

#Acceleration limits
  acc_lim_th: 2.5 
  acc_lim_x: 2.5
  acc_lim_y: 2.5
 
#Velocity limits
  max_vel_x: 1.0 #0.4
  min_vel_x: -1.0
  max_vel_y: 1.0 # 0.4
  min_vel_y: -1.0
  max_vel_trans: 2.0 #translation velocity
  min_vel_trans: 0.1 
  max_vel_theta: 1.0 #rotational velocity
  min_vel_theta: -0.8
  theta_stopped_vel: 0.01 
  trans_stopped_vel: 0.01

# Forward Simulation parameters
  sim_time: 1.7 
  sim_granularity: 0.05 
  vx_samples: 5 
  vy_samples: 10 
  vtheta_samples: 20 
  sim_period: 0.1 

# Trajectory Scoring parameters
# using default values
  goal_distance_bias: 15.0 # increase so local planner will want to move towards goal
  path_distance_bias: 7.0 # reduce so local planner wont follow the fake global plan so closely
  occdist_scale: 0.1  # increase so local planner will attempt to avoid obstacles
  stop_time_buffer: 0.2 
  oscillation_reset_dist: 0.01
  forward_point_distance: 0 #0.325 
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 

# Goal tolerance parameters
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 6.28
# latch_xy_goal_tolerance: true

