local_costmap:
  global_frame: /map ##The global frame for the costmap to operate in. 
  robot_base_frame: /base_link #The name of the frame for the base link of the robot. 
  update_frequency: 5.0 #The frequency in Hz for the map to be updated.
  publish_frequency: 5.0 #The frequency in Hz for the map to be publish display information. 
  width: 5.0 #The width of the map in meters. 
  height: 5.0 #The height of the map in meters. 
  
  static_map: false #Whether or not to use the static map to initialize the costmap
  rolling_window: true #Whether or not to use a rolling window version of the costmap.
  resolution: 0.02 #The resolution of the map in meters/cell. 

  plugins: 
        - {name: social_layer,   type: "social_navigation_layers::ProxemicLayer", output: "screen"}
        - {name: social_pass_layer,   type: "social_navigation_layers::PassingLayer", output: "screen"}
        - {name: tactile_layer,   type: "tactile_layer_namespace::TactileLayer", output: "screen"}   
        - {name: grid_layer,   type: "tactile_layer_namespace::GridLayer", output: "screen"}   



# More information at http://wiki.ros.org/costmap_2d and http://wiki.ros.org/costmap_2d/flat

#        - {name: tactile_layer,   type: "tactile_layer_namespace::TactileLayer", output: "screen"}    
#        - {name: tactile_grid_layer,   type: "tactile_layer_namespace::GridLayer", output: "screen"}   
